POST http://localhost:3003/api/blogs
Content-Type: application/json
# Burası token invalid hatası dönecek artık
{
  "title": "How to Use Redux and Redux Toolkit – Tutorial for Beginners",
  "author": "Boateng Dickson",
  "url": "https://www.freecodecamp.org/news/redux-and-redux-toolkit-for-beginners/",
  "likes": 60,
  "userId": "6776cb53202882654ff88797"
}